name: app_tcc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7
  camera: ^0.10.3+2
  path: ^1.8.2
  path_provider: ^2.0.14
  google_mlkit_commons: ^0.2.0
  google_mlkit_object_detection: ^0.6.0
  flutter_tts: ^3.6.3
  google_mlkit_text_recognition: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
